# Generated by Django 4.2.7 on 2024-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('año', models.IntegerField()),
                ('director', models.CharField(max_length=255)),
                ('poster', models.URLField()),
            ],
        ),
    ]
